#====Syetem Requirement====
#PlatinumSearcher(pt) (option, for denite.nvim)
#Processing with processing-java(for vim-processing)
#ctags (for neoinclude) <- macにデフォルトで入っているものではだめ、brewか何かで入れ直すこと。
#clang , clang-format (for vim-clang)
#
#====Vim Environment Requirement====
#+python (for jedi-vim)
#+python (for unite.vim, to use sorter_rank)
#+python (for vim-processing)
#+lua (for neocomplete.vim)
#Vim 8.0 +python3 (for denite.nvim)
#
#====Plugin Requirement====
#neosnippet-snippets.vim (for neosnippet.vim)
#neomru.vim (for denite.nvim)
#
#====Plugin Building Requirement====
#none

#load when mode='insert' and filetype='snippet'
[[plugins]]
repo='Shougo/neosnippet.vim'
depends='neosnippet-snippets'
if='has("gui_running")==0 || g:ostype!="Linux"'
on_event = ['InsertEnter']
hook_source= '''
    execute 'source' g:vim_dir.'/pluginconfig/neosnippet.config'
'''

#for neosnippet.vim
[[plugins]]
repo='Shougo/neosnippet-snippets'
on_source='neosnippet.vim'

#if cannot use Denite
[[plugins]]
repo='Shougo/unite.vim'
# if='!has("python3") || v:version < 800'
depends='neomru.vim'
on_cmd = ['Unite']
hook_add='''
    execute 'source' g:vim_dir.'/pluginconfig/unite.config'
'''
hook_post_source='''
    execute 'source' g:vim_dir.'/pluginconfig/unite_post_source.config'
'''

##if cannot use neocomplete.vim
#[[plugins]]
#repo='Shougo/neocomplcache.vim'
#if='(!has("lua") || v:version < 703) || (has("gui_running")==1 && g:ostype=="Linux")'
#on_event = ['VimEnter']
#hook_source= '''
#    execute 'source' g:vim_dir.'/pluginconfig/neocomplcache.config'
#'''

[[plugins]]
repo='tomasr/molokai'
on_source = ['denite.nvim', 'unite.vim']













##neocomplete.vimの読み込み時に一緒に読み込む
#[[plugins]]
#repo='Shougo/neoinclude.vim'
#on_source='neocomplete.vim'

##neocomplete.vimの読み込み時に一緒に読み込む
#[[plugins]]
#repo='justmao945/vim-clang'
#on_source='neocomplete.vim'
#hook_source= '''
#    execute 'source' g:vim_dir.'/pluginconfig/vim-clang.config'
#'''

##neocomplete.vimの読み込み時に一緒に読み込む
#[[plugins]]
#repo='Shougo/neco-syntax'
#on_source='neocomplete.vim'

##python3導入済、かつ特定のコマンドを入力したら読み込む
#[[plugins]]
#repo='Shougo/denite.nvim'
#if='has("python3") && v:version >= 800'
#depends='neomru.vim'
#hook_add='''
#    execute 'source' g:vim_dir.'/pluginconfig/denite.config'
#'''
#hook_post_source='''
#    execute 'source' g:vim_dir.'/pluginconfig/denite_post_source.config'
#'''

##tex編集時に読み込み
#[[plugins]]
#repo='lervag/vimtex'
#on_ft='tex'
#hook_source= '''
#    execute 'source' g:vim_dir.'/pluginconfig/vimtex.config'
#'''

##pde編集時に読み込み
#[[plugins]]
#repo='sophacles/vim-processing'
#on_ft='processing'
#hook_source='''
#    execute 'source' g:vim_dir.'/pluginconfig/vim-processing.config'
#'''

##インサートモードの時に読み込む
#[[plugins]]
#repo='cohama/lexima.vim'
#on_i=1
#if='has("gui_running")==0||g:ostype!="Linux"'
#hook_post_source='''
#    execute 'source' g:vim_dir.'/pluginconfig/lexima.config'
#    execute 'source' g:vim_dir.'/pluginconfig/cooperation_of_plugins.config'
#'''

#python編集時に読み込み
#[[plugins]]
#repo='davidhalter/jedi-vim'
#on_ft='python'
#hook_source='''
#    execute 'source' g:vim_dir.'/pluginconfig/jedi-vim.config'
#'''

##lua導入済み、かつインサートモードの時に読み込む
#[[plugins]]
#repo='Shougo/neocomplete.vim'
#if='(has("lua") && v:version >= 703) && (has("gui_running")==0 || g:ostype!="Linux")'
#on_i=1
#hook_source= '''
#    execute 'source' g:vim_dir.'/pluginconfig/neocomplete.config'
#    execute 'source' g:vim_dir.'/pluginconfig/cooperation_of_plugins.config'
#'''

